services:
  - type: web
    name: swasya-ai
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: MONGODB_DB_NAME
        value: swasya_ai
      - key: MONGODB_URI
        sync: false
      - key: SECRET_KEY
        generateValue: true
